# Generated by Django 5.0.4 on 2024-12-22 23:11

import shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=shop_app.models.product_preview_directory_path),
        ),
    ]
