# Generated by Django 5.0.4 on 2025-01-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_alter_order_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='delivery address'),
        ),
    ]
